common: &common
  adapter: postgresql
  username: codabra
  password: codabra

development:
  <<: *common
  database: codabra_development

test:
  <<: *common
  database: codabra_test

production:
  <<: *common
  database: codabra_production
